routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Web'], function() {
    Route::get('/', 'HomeController@index')->name('home');
});

Route::namespace('Admin')->name('admin.')->prefix('admin')->group(function() {
    Route::get('/agents', 'AgentController@index')->name('agent.index');
    Route::get('/agent/create', 'AgentController@create')->name('agent.create');
    Route::post('/agent/store', 'AgentController@store')->name('agent.store');
    Route::get('/agent/show/{agent}', 'AgentController@show')->name('agent.show');
    Route::get('/agent/edit/{agent}', 'AgentController@edit')->name('agent.edit');
    Route::put('/agent/update/{agent}', 'AgentController@update')->name('agent.update');
    Route::delete('/agent/delete/{agent}', 'AgentController@destroy')->name('agent.delete');
});

app/Models/Agent.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Agent extends Model
{
    use HasFactory;

    protected $fillable = [
        'full_name',
        'email',
        'phone',
        'mobile',
        'address',
    ];


    public function properties()
    {
        return $this->belongsToMany(Property::class, 'agent_property', 'agent_id', 'property_id');
    }

    public function getTotalPriceAttribute()
    {

        $data = $this->properties->sum(function($query) {
             return $query->price;
        });

        return $data;
    }

}

app/Models/AgentProperty.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class AgentProperty extends Model
{

    protected $table = "agent_property";

    protected $fillable = [
        'agent_id',
        'property_id',
    ];
}

app/Models/Property.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Property extends Model
{
    use HasFactory;

    public $incrementing = false;

    protected $fillable = [
        'id',
        'property_type_id',
        'image_full',
        'image_thumbnail',
        'county',
        'country',
        'town',
        'address',
        'num_bedrooms',
        'num_bathrooms',
        'description',
        'type',
        'price',
        'latitude',
        'longitude',
    ];

    protected $appends = ['url'];

    public function property_type()
    {
        return $this->belongsTo(PropertyType::class, 'property_type_id');
    }

    public function agents()
    {
        return $this->belongsToMany(Agent::class, 'agent_property', 'property_id', 'agent_id');
    }

    public function getUrlAttribute()
    {
        return route('api.property.show', [$this->id]);
    }

}

app/Models/PropertyType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PropertyType extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'title',
        'description',
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/AgentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Agent;
use App\Models\Property;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

class AgentController extends Controller
{

    public function show($id)
    {
        return Agent::find($id);
    }

    public function create()
    {
        $properties = Property::get()->pluck('country', 'id');
        return view('admin.agents.create',compact('properties'));
    }


    public function store(Request $request)
    {
        // Add validation rules
        $validated = $request->validate([
            'full_name' => 'required|max:255',
            'email' => 'required|unique:agents',
            'phone' => 'required|max:15',
            'mobile' => 'required|max:15',
            'address' => 'required',
        ]);

        $properties = $request->input('properties');
        $agent = Agent::create($request->except('properties'));
        $agent->properties()->sync($properties);

        return redirect()->route('agent.index');
    }

    public function edit($id)
    {
        $agent = Agent::findOrFail($id);
        $properties = Property::get()->pluck('country', 'id');

        return view('admin.agents.create',compact('agent', 'properties'));
    }

    public function update(Request $request, $id)
    {
        $agent = Agent::findOrFail($id);
        $agent->update($request->all());

        return $agent;
    }

    public function destroy(Request $request, $id)
    {
        $agent = Agent::findOrFail($id);
        $agent->delete();

        return redirect()->route('agent.index');
    }
}

app/Http/Controllers/Admin/PropertyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Property;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

class PropertyController extends Controller
{
    public function index()
    {
        return Property::all();
    }

    public function show($id)
    {
        return Property::find($id);
    }

    public function store(Request $request)
    {
        return Property::create($request->all());
    }

    public function edit($id)
    {
        return Property::find($id);
    }

    public function update(Request $request, $id)
    {
        $property = Property::findOrFail($id);
        $property->update($request->all());

        return $property;
    }

    public function destroy(Request $request, $id)
    {
        $property = Property::findOrFail($id);
        $property->delete();

        return 204;
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Web/HomeController.php
<?php

namespace App\Http\Controllers\Web;

use App\Models\Property;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

class HomeController extends Controller
{
     /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        return view('web.index');
    }

}

resources/views/admin/agents/create.blade.php
@extends('admin.layouts.master')

@section('title', 'Add Agent')

@section('content')
<section>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h4>Add agent</h4>
                <form method="POST" action="{{route('admin.agent.store')}}">
                    @csrf
                    <div class="form-group">
                        <label for="full_name">Full name</label>
                        <input type="text" name="full_name" class="form-control" id="full_name" value="{{ old('full_name', $agent->full_name ?? '') }}">
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="text" name="email" class="form-control" id="email" value="{{ old('email', $agent->email ?? '') }}">
                    </div>

                    <div class="form-group">
                        <label for="phone">Phone</label>
                        <input type="text" name="phone" class="form-control" id="phone" value="{{ old('phone', $agent->phone ?? '') }}">
                    </div>

                    <div class="form-group">
                        <label for="mobile">Mobile</label>
                        <input type="text" name="mobile" class="form-control" id="mobile" value="{{ old('mobile', $agent->mobile ?? '') }}">
                    </div>

                    <div class="form-group">
                        <label for="address">Address</label>
                        <input type="text" name="address" class="form-control" id="address" value="{{ old('address', $agent->address ?? '') }}">
                    </div>

                    @if($properties)
                    <div class="form-group">
                        <label for="address">Properties</label>
                        <select class="form-control" name="properties" multiple>
                            @foreach($properties as $key => $property)
                            <option value="{{$key}}">{{$property}}</option>
                            @endforeach
                        </select>
                    </div>
                    @else
                    <div class="alert alert-info">To import properties run <code>php artisan import:data</code></div>
                    @endif
                    <div class="mt-3">
                        @if(empty($agent))
                        <button type="submit" class="btn btn-primary btn-block">Add agent</button>
                        @else
                        <button type="submit" class="btn btn-primary btn-block">Update agent</button>
                        @endif
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
@stop

resources/views/admin/layouts/master.blade.php
<html>
    <head>
        <title>Admin - @yield('title')</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container">
            @yield('content')
        </div>
        @include('admin.partials.footer')
    </body>
</html>

resources/views/admin/partials/footer.blade.php
<footer class="mt-5">
    <div class="container">
        <div class="col-12">
            <p class="text-muted">Copyright {{ date('Y') }} - CoronaStreet</p>
        </div>
    </div>
</footer>

resources/views/web/index.blade.php
@extends('web.layouts.master')

@section('title', 'Home')


@section('content')
<section>
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1 class="text-center mb-5">Home</h1>
            </div>
            <div class="col-md-6">
                <div class="card mb-5">
                    <div class="card-body">
                        <h4>Add Agent</h4>
                        <p>Add:: agents to our database</p>
                        <a href="{{route('admin.agent.create')}}" class="stretched-link"></a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card mb-5">
                    <div class="card-body">
                        <h4>Properties</h4>
                        <p>View:: all properties in our database
                        <a href="{{route('api.property.index')}}" class="stretched-link"></a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card mb-5">
                    <div class="card-body">
                        <h4>Agents</h4>
                        <p>View:: all agents in our database
                        <a href="{{route('api.agent.index')}}" class="stretched-link"></a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card mb-5">
                    <div class="card-body">
                        <h4>Top Agents</h4>
                        <p>View:: Top agents in our database
                        <a href="{{route('api.agent.top')}}" class="stretched-link"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@stop

resources/views/web/layouts/master.blade.php
<html>
    <head>
        <title>@yield('title')</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container">
            @yield('content')
        </div>
        @include('web.partials.footer')
    </body>
</html>

resources/views/web/partials/footer.blade.php
<footer class="mt-5">
    <div class="container text-center">
        <div class="col-12">
            <p class="text-muted">Copyright {{ date('Y') }} - CoronaStreet</p>
        </div>
    </div>
</footer>